---
title: Toán Tiếng Anh
timezone: Asia/Bangkok
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    image: "/assets/img/trada_cover.png"
author: Thầy Bá Phong
email: baphong80@gmail.com
description: 'Trang web chia sẻ các đề thi Toán Tiếng Anh quốc tế, đồng thời
  hỗ trợ người học tra cứu theo [Dạng Toán](dangtoan.html), [Từ vựng](tuvung.html)
  và [Ngữ pháp](nguphap.html).

'
twitter_username: baphong80
github_username: baphong
rss: rss
show_excerpts: false
header_pages:
- dethi.md
- dangtoan.md
- tuvung.md
- nguphap.md
minima:
  date_format: "%b %-d, %Y"
theme: minima
plugins:
- jekyll-feed
- jekyll-seo-tag
