---
title: emath.cf
timezone: Asia/Bangkok
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    image: "/assets/img/trada_cover.png"
lang: vi
description: Đề thi Toán Tiếng Anh quốc tế
baseurl: "/"
url: https://emath.cf
google_analytics: UA-8597504-5
markdown: kramdown
theme: minima
show_excerpts: true
header_pages:
- tuvung.md
- nguphap.md
- dethi.md
- dangtoan.md
plugins:
- jekyll-feed
jekyll_admin:
  hidden_links:
  - posts
  - pages
  - staticfiles
  - datafiles
  - configuration
