---
title: emath.cf
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    image: "/assets/img/trada_cover.png"
lang: vi
description: Đề thi Toán Tiếng Anh quốc tế
baseurl: "/"
url: https://emath.cf
google_analytics: UA-8597504-5
markdown: kramdown
theme: minima
show_excerpts: true
header_pages:
- consulting.md
- courses.md
- blog.md
plugins:
- jekyll-feed
